### ISSUE TITLE
Problem with inhouse endpoint

### ISSUE THREAD

**Issue by mavdi** [gyllstromk/grunt-bowerful#3]
Hi,

It seems the plugin has a problem with handling inhouse and bower heroku search points at the same time. This is what I use in my `~/.bowerrc` file:

``` javascript
{
  "endpoint" : "http://inhousebower:4567",
  "searchpath" : ["https://bower.herokuapp.com"]
}
```

When adding components, it loads up the ones on the inhouse end point, but not the ones on bower search path. (bower command itself works)

Here is the error I get

```
Error: jquery not found
    at Request.exports.lookup [as _callback] (/Users/mavdi/work/framework/node_modules/grunt-bowerful/node_modules/bower/lib/core/source.js:20:68)
    at Request.init.self.callback (/Users/mavdi/work/framework/node_modules/grunt-bowerful/node_modules/bower/node_modules/request/main.js:122:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/Users/mavdi/work/framework/node_modules/grunt-bowerful/node_modules/bower/node_modules/request/main.js:655:16)
    at Request.EventEmitter.emit (events.js:126:20)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/Users/mavdi/work/framework/node_modules/grunt-bowerful/node_modules/bower/node_modules/request/main.js:617:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1367:20)
```

Removing the `~/.bowerrc` file fixes the problem, but then the plugin will be unable to load the in house modules.

Any ideas?

**Comment by mavdi** [comment]
Maybe missing something here, but I'm wondering why the bower command API is not being used instead of accessing the classes directly?

**Comment by gyllstromk** [comment]
What do you mean by command API? You mean running the ./bin/bower script?

**Comment by mavdi** [comment]
Here is what I got from bower docs:

``` javascript
var bower = require('bower');

bower.commands
  .install(paths, options)
  .on('end', function (data) {
    data && console.log(data);
  });
```

This could make things easier for you.

**Comment by gyllstromk** [comment]
Thanks for the tip. I've updated to use this, as well as to be compliant with grunt 4.

**Comment by mavdi** [comment]
Thanks :smile:
We can start using this again.
